
```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=8, fig.height=8,
                      echo=FALSE, warning=FALSE, message=FALSE)
```


```{r }
#Author: Mark Dane, copyright 2015

source("./MEPLINCSFunctions.R")

```



```{r setup,cache=FALSE}
library("ggplot2")
library("data.table")
library("MEMA")
library("grid")
library("knitr")
library("gplots")
library("RColorBrewer")
library(DT)
library(d3heatmap)
library(plotly)
library(corrplot)
library(Rtsne)

#Setup colors for Barcode and text in all heatmaps
selDark2 <- colorRampPalette(brewer.pal(8,"Dark2"))
plateCol = selDark2(8)
hmcols<-colorRampPalette(c("blue","white","red"))(16)


#PC3_SS2_l4 <- fread("./PC3/SS2/AnnotatedData/PC3_SS2_v2.1_av1.4_Level4.txt", showProgress = FALSE)
SS2StainingSet <- "SS2noH3"
PC3_SS2_l4 <- fread(paste0("./PC3/SS2noH3/AnnotatedData/PC3_",SS2StainingSet,"_v1_av1.4_Level4.txt"), showProgress = FALSE)

#Remove the FBS MEPs
PC3_SS2_l4 <- PC3_SS2_l4[!grepl("FBS",PC3_SS2_l4$MEP)]
sPC3_SS2_l4 <- PC3_SS2_l4[,list(MEP,Spot_PA_SpotCellCount,Spot_PA_SpotCellCountLog2RUV3,Spot_PA_SpotCellCountLog2RUV3Loess,Nuclei_PA_Cycle_DNA2NProportionLogitRUV3,Nuclei_PA_Gated_EduPositiveProportionRUV3Loess,Nuclei_PA_Gated_EduPositiveProportionRUV3)]
signalNames <- grep("MEP",colnames(sPC3_SS2_l4), value=TRUE,invert=TRUE)
setnames(sPC3_SS2_l4,signalNames,paste("SS2",signalNames,sep="_"))
setkey(sPC3_SS2_l4,MEP)

SS3StainingSet <- "SS3"
PC3_SS3_l4 <- fread(paste0("./PC3/SS3/AnnotatedData/PC3_",SS3StainingSet,"_v2.1_av1.4_Level4.txt"), showProgress = FALSE)
#Remove the FBS MEPs
PC3_SS3_l4 <- PC3_SS3_l4[!grepl("FBS",PC3_SS3_l4$MEP)]
#Keep columns of interest
sPC3_SS3_l4 <- PC3_SS3_l4[,list(MEP,Spot_PA_SpotCellCount,Spot_PA_SpotCellCountLog2RUV3,Spot_PA_SpotCellCountLog2RUV3Loess,Nuclei_PA_Cycle_DNA2NProportionLogitRUV3,Cytoplasm_PA_Intensity_LineageRatioLog2RUV3,Cytoplasm_PA_Intensity_LineageRatioLog2RUV3Loess)]
signalNames <- grep("MEP",colnames(sPC3_SS3_l4), value=TRUE,invert=TRUE)
setnames(sPC3_SS3_l4,signalNames,paste("SS3",signalNames,sep="_"))
setkey(PC3_SS3_l4,MEP)

PC3_SS3_SS2 <- merge(sPC3_SS2_l4,sPC3_SS3_l4)

write.csv(PC3_SS3_SS2, file = "PC3_SS3_SS2noH3.csv",quote = FALSE,row.names = FALSE)


```

The plots in this report are from the PC3 `r SS3StainingSet` lineage staining set and the PC3 `r SS2StainingSet`proliferation staining set. The plots are a combination of raw, RUV3 normalized and RUV3Loess normalized values.


```{r LineageRatiovsEdURUVLoess, fig.width=8, fig.height=6}

dt <- PC3_SS3_SS2

p <- ggplot(dt, aes(x =SS2_Nuclei_PA_Gated_EduPositiveProportionRUV3Loess, y = SS3_Cytoplasm_PA_Intensity_LineageRatioLog2RUV3Loess, colour=MEP))+
  geom_point()+
  guides(colour=FALSE)+
  xlab("Normalized EdU+ Proportion")+ylab("Normalized Lineage Ratio")+
  theme(axis.ticks=element_blank(),  panel.grid.major = element_blank())+
  ggtitle("MEP Lineage Ratio vs EdU+ Proportion (RUV Loess)")

print(p)

```

```{r LineageRatiovsEdU, fig.width=8, fig.height=6}

dt <- PC3_SS3_SS2

p <- ggplot(dt, aes(x =SS2_Nuclei_PA_Gated_EduPositiveProportionRUV3, y = SS3_Cytoplasm_PA_Intensity_LineageRatioLog2RUV3, colour=MEP))+
  geom_point()+
  guides(colour=FALSE)+
  xlab("Normalized EdU+ Proportion")+ylab("Normalized Lineage Ratio")+
  theme(axis.ticks=element_blank(),  panel.grid.major = element_blank())+
  ggtitle("MEP Lineage Ratio vs EdU+ Proportion (RUV)")

print(p)

```


```{r LineageRatiovsSpotCellCount, fig.width=8, fig.height=6}

dt <- PC3_SS3_SS2

p <- ggplot(dt, aes(x =SS3_Spot_PA_SpotCellCountLog2RUV3, y = SS3_Cytoplasm_PA_Intensity_LineageRatioLog2RUV3, colour=MEP))+
  geom_point()+
  guides(colour=FALSE)+
  xlab("Normalized Spot Cell Count")+ylab("Normalized Lineage Ratio")+
  theme(axis.ticks=element_blank(),  panel.grid.major = element_blank())+
  ggtitle("MEP Lineage Ratio vs Spot Cell Count (RUV SS3)")

print(p)

```

```{r LineageRatiovsDN2N, fig.width=8, fig.height=6}

dt <- PC3_SS3_SS2

p <- ggplot(dt, aes(x =SS2_Nuclei_PA_Cycle_DNA2NProportionLogitRUV3, y = SS3_Cytoplasm_PA_Intensity_LineageRatioLog2RUV3, colour=MEP))+
  geom_point()+
  guides(colour=FALSE)+
  xlab("Normalized DNA 2N Proportion")+ylab("Normalized Lineage Ratio")+
  theme(axis.ticks=element_blank(),  panel.grid.major = element_blank())+
  ggtitle("MEP Lineage Ratio vs DNA 2N Proportion (RUV)")

print(p)

```

```{r datatable}
colNamesDisplay <- gsub("_","\n",gsub("Spot|Nuclei|Cytoplasm|PA|Cycle","",colnames(dt)))

datatable(format(dt[, colnames(dt), with=FALSE], digits=2, scientific = FALSE, nsmall=0), options = list(pageLength = 5), colnames = colNamesDisplay)
```

```{r SccvsSCC, fig.width=8, fig.height=6}

dt <- PC3_SS3_SS2

p <- ggplot(dt, aes(x =SS2_Spot_PA_SpotCellCount, y = SS3_Spot_PA_SpotCellCount, colour=MEP))+
  geom_point()+
  guides(colour=FALSE)+
  xlab("Spot Cell Count")+ylab("Spot Cell Count")+
  theme(axis.ticks=element_blank(),  panel.grid.major = element_blank())+
  ggtitle("MEP SS3 Spot Cell Count vs SS2 Spot Cell Count (Raw)")

print(p)

```

```{r NormedSccvsNormedSCC, fig.width=8, fig.height=6}

dt <- PC3_SS3_SS2

p <- ggplot(dt, aes(x =SS2_Spot_PA_SpotCellCountLog2RUV3, y = SS3_Spot_PA_SpotCellCountLog2RUV3, colour=MEP))+
  geom_point()+
  guides(colour=FALSE)+
  xlab("Normalized Spot Cell Count")+ylab("Normalized Spot Cell Count")+
  theme(axis.ticks=element_blank(),  panel.grid.major = element_blank())+
  ggtitle("MEP SS3 Spot Cell Count vs SS2 Spot Cell Count (RUV)")

print(p)

```


```{r NormedRUV3LoessSccvsNormedRUV3LoessSCC, fig.width=8, fig.height=6}

dt <- PC3_SS3_SS2

p <- ggplot(dt, aes(x =SS2_Spot_PA_SpotCellCountLog2RUV3Loess, y = SS3_Spot_PA_SpotCellCountLog2RUV3Loess, colour=MEP))+
  geom_point()+
  guides(colour=FALSE)+
  xlab("Normalized Spot Cell Count")+ylab("Normalized Spot Cell Count")+
  theme(axis.ticks=element_blank(),  panel.grid.major = element_blank())+
  ggtitle("MEP SS3 Spot Cell Count vs SS2 Spot Cell Count (RUV Loess)")

print(p)

```
