---
output: html_document
---

---
title: "Spot Population Responses"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=20,
                      echo=FALSE, warning=FALSE, message=FALSE)
```


```{r }
#Author: Mark Dane, copyright 2015

source("MEPLINCSFunctions.R")
  
#Set the cell line to be analyzed (PC3|MCF7|YAPC)
cellLine <- "PC3"
extremePercent<- 1

library("ggplot2")
library("data.table")
library("MEMA")
library("grid")
library(knitr)
library("gplots")
library("RColorBrewer")

```

```{r LineageOuter, eval=TRUE}
#After extensive review of images, the differences are all driven by few cells

l2 <- fread(paste0("./",cellLine,"/SS3/AnnotatedData/",cellLine,"_SS3_Level2.txt"), showProgress = FALSE)
l2$Spot_PA_OuterCell <- as.logical(gsub(" ","",l2$Spot_PA_OuterCell))
l2$Spot_PA_Sparse <- as.logical(gsub(" ","",l2$Spot_PA_Sparse))
l2$Spot_PA_Perimeter <- as.logical(gsub(" ","",l2$Spot_PA_Perimeter))

barcodes <- unique(l2$Barcode)
lthresh <- 0.6

DT <- copy(l2)
#Remove the fiducial entries
setkey(DT,ECMp)
DT <- DT[!"fiducial"]
DT <- DT[!"blank"]
DT <- DT[!"NID1"]
#Add a lineageRatio based on the spot normalized KRT values
DT$Cytoplasm_PA_Intensity_LineageRatio_SpotNorm <- DT$Cytoplasm_CP_Intensity_MedianIntensity_KRT19_SpotNorm/DT$Cytoplasm_CP_Intensity_MedianIntensity_KRT5_SpotNorm

DT <- DT[DT$Spot_PA_SpotCellCount > 20]

DT <- DT[,LineageOuterRatio := calcGroupRatios(.SD, "Spot_PA_OuterCell", "Cytoplasm_PA_Intensity_LineageRatio_SpotNorm"), by = Spot ]

diffOuterLineageMEPS <- unique(DT$MEP[DT$LineageOuterRatio < quantile(DT$LineageOuterRatio, extremePercent*.005) | DT$LineageOuterRatio > quantile(DT$LineageOuterRatio, 1-extremePercent*.005)])

sDT <- unique(DT[DT$MEP %in% diffOuterLineageMEPS, list(MEP,LineageOuterRatio,Spot)])
sDT <- sDT[,ReplicateCount := .N, by=MEP]
mDT <- sDT[, LineageOuterRatio := median(LineageOuterRatio), by="MEP"]
mDT <- mDT[,Spot :=NULL]
mDT <- unique(mDT)

setkey(mDT, LineageOuterRatio)
mDT$MEP <- reorder(mDT$MEP,mDT$LineageOuterRatio)
DT$MEP <- factor(DT$MEP, levels=unique(mDT$MEP), ordered=TRUE)

setkey(DT,MEP)

p  <- ggplot(DT[DT$MEP %in% diffOuterLineageMEPS], aes(x = Spot_PA_OuterCell, y = Cytoplasm_PA_Intensity_LineageRatio_SpotNorm))+
  geom_boxplot()+
  #ylim(.25,1.75)+
  ylab("Lineage Ratio")+xlab("Outer Cells (True)")+
  ggtitle(paste("Lineage Ratios in Outer vs. Inner Cells\nin Extreme",extremePercent, "Percent Differential Response (True is Outer)"))+
  facet_wrap(~MEP, ncol = 10)+
  theme(strip.text = element_text(size = rel(.5)))
print(p)

kable(mDT, digits = 2, align = "l")

#unique(DT[DT$MEP=="DSG2_LYVE1",list(Barcode,Well,Spot,ArrayRow,ArrayColumn)])

```


```{r LineageSparse, eval=TRUE}

l2 <- fread(paste0("./",cellLine,"/SS3/AnnotatedData/",cellLine,"_SS3_Level2.txt"), showProgress = FALSE)
l2$Spot_PA_OuterCell <- as.logical(gsub(" ","",l2$Spot_PA_OuterCell))
l2$Spot_PA_Sparse <- as.logical(gsub(" ","",l2$Spot_PA_Sparse))
l2$Spot_PA_Perimeter <- as.logical(gsub(" ","",l2$Spot_PA_Perimeter))

barcodes <- unique(l2$Barcode)
lthresh <- 0.6

DT <- copy(l2)
#Remove the fiducial entries
setkey(DT,ECMp)
DT <- DT[!"fiducial"]
DT <- DT[!"blank"]
DT <- DT[!"NID1"]

#Add a lineageRatio based on the spot normalized KRT values
DT$Cytoplasm_PA_Intensity_LineageRatio_SpotNorm <- DT$Cytoplasm_CP_Intensity_MedianIntensity_KRT19_SpotNorm/DT$Cytoplasm_CP_Intensity_MedianIntensity_KRT5_SpotNorm

DT <- DT[DT$Spot_PA_SpotCellCount > 30]

DT <- DT[,LineageSparseRatio := calcGroupRatios(.SD, "Spot_PA_Sparse", "Cytoplasm_PA_Intensity_LineageRatio_SpotNorm"), by = Spot ]

diffSparseLineageMEPS <- unique(DT$MEP[DT$LineageSparseRatio < quantile(DT$LineageSparseRatio, extremePercent*.005, na.rm = TRUE) | DT$LineageSparseRatio > quantile(DT$LineageSparseRatio, 1-extremePercent*.005, na.rm = TRUE)])

sDT <- unique(DT[DT$MEP %in% diffSparseLineageMEPS, list(MEP,LineageSparseRatio,Spot)])
sDT <- sDT[,ReplicateCount := .N, by=MEP]
mDT <- sDT[, LineageSparseRatio := median(LineageSparseRatio), by="MEP"]
mDT <- mDT[,Spot :=NULL]
mDT <- unique(mDT)

setkey(mDT, LineageSparseRatio)
mDT$MEP <- reorder(mDT$MEP,mDT$LineageSparseRatio)
DT$MEP <- factor(DT$MEP, levels=unique(mDT$MEP), ordered=TRUE)

setkey(DT,MEP)

p  <- ggplot(DT[DT$MEP %in% diffSparseLineageMEPS], aes(x = Spot_PA_OuterCell, y = Cytoplasm_PA_Intensity_LineageRatio_SpotNorm))+
  geom_boxplot()+
  #ylim(.25,1.75)+
  ylab("Lineage Ratio")+xlab("Sparse Cells (True)")+
  ggtitle(paste("Lineage Ratios in Sparse vs. Dense Cells\nin Extreme",extremePercent, "Percent Differential Response (True is Outer)"))+
  facet_wrap(~MEP, ncol = 10)+
  theme(strip.text = element_text(size = rel(.5)))
print(p)

kable(mDT, digits = 2, align = "l")

#unique(DT[DT$MEP=="BCAN_JAG1",list(Barcode,Well,Spot,ArrayRow,ArrayColumn)])



```


```{r MitOuterRatio,fig.height=10, eval=TRUE}

l2 <- fread(paste0("./",cellLine,"/SS1/AnnotatedData/",cellLine,"_SS1_Level2.txt"), showProgress = FALSE)
l2$Spot_PA_OuterCell <- as.logical(gsub(" ","",l2$Spot_PA_OuterCell))
l2$Spot_PA_Sparse <- as.logical(gsub(" ","",l2$Spot_PA_Sparse))
l2$Spot_PA_Perimeter <- as.logical(gsub(" ","",l2$Spot_PA_Perimeter))

barcodes <- unique(l2$Barcode)
lthresh <- 0.6

DT <- copy(l2)
#Remove the fiducial entries
setkey(DT,ECMp)
DT <- DT[!"fiducial"]
DT <- DT[!"blank"]
DT <- DT[!"NID1"]

DT <- DT[DT$Spot_PA_SpotCellCount > 25]

DT <- DT[,MitoOuterRatio := calcGroupRatios(.SD, "Spot_PA_OuterCell", "Cytoplasm_CP_Intensity_MedianIntensity_MitoTracker_SpotNorm"), by = MEP ]

diffOuterMitoMEPS <- unique(DT$MEP[DT$MitoOuterRatio < quantile(DT$MitoOuterRatio, extremePercent*.005) | DT$MitoOuterRatio > quantile(DT$MitoOuterRatio, 1-extremePercent*.005)])

sDT <- unique(DT[DT$MEP %in% diffOuterMitoMEPS, list(MEP,MitoOuterRatio,Spot)])
sDT <- sDT[,ReplicateCount := .N, by=MEP]
mDT <- sDT[,MitoOuterRatio := median(MitoOuterRatio), by = MEP]
mDT <- mDT[,Spot :=NULL]
mDT <- unique(mDT)

setkey(mDT, MitoOuterRatio)
mDT$MEP <- reorder(mDT$MEP,mDT$MitoOuterRatio)
DT$MEP <- factor(DT$MEP, levels=unique(mDT$MEP), ordered=TRUE)

setkey(DT,MEP)

p  <- ggplot(DT[DT$MEP %in% diffOuterMitoMEPS], aes(x = Spot_PA_OuterCell, y = Cytoplasm_CP_Intensity_MedianIntensity_MitoTracker_SpotNorm))+
  geom_boxplot()+
  #ylim(1,2.5)+
  ylab("MitoTracker Intensity")+xlab("Outer Cells (True)")+
  ggtitle(paste("MitoTracker Intensity in Outer vs. Inner Cells\nin Extreme",extremePercent, "Percent Differential Response (True is Outer)"))+
  facet_wrap(~MEP, ncol = 10)+
  theme(strip.text = element_text(size = rel(.5)))
print(p)


kable(mDT, digits = 2, align = "l")

#unique(DT[DT$MEP=="BCAN_JAG1",list(Barcode,Well,Spot,ArrayRow,ArrayColumn)])

```


```{r MitPerimeterRatio,fig.height=20, eval=TRUE}

l2 <- fread(paste0("./",cellLine,"/SS1/AnnotatedData/",cellLine,"_SS1_Level2.txt"), showProgress = FALSE)
l2$Spot_PA_OuterCell <- as.logical(gsub(" ","",l2$Spot_PA_OuterCell))
l2$Spot_PA_Sparse <- as.logical(gsub(" ","",l2$Spot_PA_Sparse))
l2$Spot_PA_Perimeter <- as.logical(gsub(" ","",l2$Spot_PA_Perimeter))

barcodes <- unique(l2$Barcode)
lthresh <- 0.6

DT <- copy(l2)
#Remove the fiducial entries
setkey(DT,ECMp)
DT <- DT[!"fiducial"]
DT <- DT[!"blank"]
DT <- DT[!"NID1"]

DT <- DT[DT$Spot_PA_SpotCellCount > 25]

DT <- DT[,MitoPermRatio := calcGroupRatios(.SD, "Spot_PA_Perimeter", "Cytoplasm_CP_Intensity_MedianIntensity_MitoTracker_SpotNorm"), by = MEP ]

diffPermMitoMEPS <- unique(DT$MEP[DT$MitoPermRatio < quantile(DT$MitoPermRatio, extremePercent*.005) | DT$MitoPermRatio > quantile(DT$MitoPermRatio, 1-extremePercent*.005)])

sDT <- unique(DT[DT$MEP %in% diffPermMitoMEPS, list(MEP,MitoPermRatio,Spot)])
sDT <- sDT[,ReplicateCount := .N, by=MEP]
mDT <- sDT[,MitoPermRatio := median(MitoPermRatio), by = MEP]
mDT <- mDT[,Spot :=NULL]
mDT <- unique(mDT)

setkey(mDT, MitoPermRatio)
mDT$MEP <- reorder(mDT$MEP,mDT$MitoPermRatio)
DT$MEP <- factor(DT$MEP, levels=unique(mDT$MEP), ordered=TRUE)

setkey(DT,MEP)

p  <- ggplot(DT[DT$MEP %in% diffPermMitoMEPS], aes(x = Spot_PA_Perimeter, y = Cytoplasm_CP_Intensity_MedianIntensity_MitoTracker_SpotNorm))+
  geom_boxplot()+
  #ylim(1,2.5)+
  ylab("MitoTracker Intensity")+xlab("Perimeter Cells (True)")+
  ggtitle(paste("MitoTracker Intensity in Perimeter vs. Interior Cells\nin Extreme",extremePercent, "Percent Differential Response (True is Outer)"))+
  facet_wrap(~MEP, ncol = 10)+
  theme(strip.text = element_text(size = rel(.5)))
print(p)


kable(mDT, digits = 2, align = "l")

#unique(DT[DT$MEP=="DCN_LYVE1",list(Barcode,Well,Spot,ArrayRow,ArrayColumn)])
kable(unique(DT[DT$MEP %in% diffPermMitoMEPS,list(MEP, Barcode,Well,Spot,ArrayRow,ArrayColumn)]), digits = 2,align = "l")

```


```{r MitPerimeterImages,fig.height=55, eval=TRUE}
p <- ggplot(DT[DT$MEP %in% diffPermMitoMEPS], aes(x=Nuclei_PA_Centered_X, y = Nuclei_PA_Centered_Y, size = Nuclei_CP_AreaShape_Area, colour = Spot_PA_Perimeter, fill = log2(Cytoplasm_CP_Intensity_MedianIntensity_MitoTracker_SpotNorm)))+
geom_point(shape = 21)+scale_size_area(max_size = 12)+
  scale_color_manual(values = c("transparent","white"))+
  scale_fill_gradient(low="black", high="red")+
  scale_y_reverse()+
  guides(fill=FALSE, colour=FALSE, size = FALSE)+
  facet_wrap(~Spot, ncol = 4)
print(p)

```

```{r EdUOuterRatio,fig.height=10, eval=TRUE}

extremePercent <- 5

l2 <- fread(paste0("./",cellLine,"/SS2/AnnotatedData/",cellLine,"_SS2_Level2.txt"), showProgress = FALSE)
l2$Spot_PA_OuterCell <- as.logical(gsub(" ","",l2$Spot_PA_OuterCell))
l2$Spot_PA_Sparse <- as.logical(gsub(" ","",l2$Spot_PA_Sparse))
l2$Spot_PA_Perimeter <- as.logical(gsub(" ","",l2$Spot_PA_Perimeter))

barcodes <- unique(l2$Barcode)
lthresh <- 0.6

DT <- copy(l2)
#Remove the fiducial entries
setkey(DT,ECMp)
DT <- DT[!"fiducial"]
DT <- DT[!"blank"]
DT <- DT[!"NID1"]

DT <- DT[DT$Spot_PA_SpotCellCount > 20]

calcGroupRatiosMean <- function(x,group,signal){
  #browser()
  meanInGroup <- mean(x[[signal]][x[[group]]], na.rm=TRUE)
  meanOutGroup <- mean(x[[signal]][!x[[group]]], na.rm=TRUE)
  return(meanInGroup/meanOutGroup)
}

DT <- DT[,EduDenseRatio := calcGroupRatiosMean(.SD, "Spot_PA_Sparse", "Nuclei_PA_Gated_EduPositiveProportion"), by = MEP ]

diffEduDenseMEPS <- unique(DT$MEP[DT$EduDenseRatio < quantile(DT$EduDenseRatio, extremePercent*.005, na.rm = TRUE) | DT$EduDenseRatio > quantile(DT$EduDenseRatio, 1-extremePercent*.005, na.rm = TRUE)])

#Create a MEP and rati DT to create ordered factors
sDT <- unique(DT[DT$MEP %in% diffEduDenseMEPS, list(MEP,Spot, EduDenseRatio)])
sDT <- sDT[,ReplicateCount := .N, by=MEP]
mDT <- sDT[,EduDenseRatio := mean(EduDenseRatio), by = MEP]
mDT <- mDT[,Spot :=NULL]
mDT <- unique(mDT)

setkey(mDT, EduDenseRatio)
mDT$MEP <- reorder(mDT$MEP,mDT$EduDenseRatio)
DT$MEP <- factor(DT$MEP, levels=unique(mDT$MEP), ordered=TRUE)

setkey(DT,MEP)

p  <- ggplot(DT[DT$MEP %in% diffEduDenseMEPS], aes(x = Spot_PA_Sparse, y = Nuclei_PA_Gated_EduPositiveProportion))+
  geom_boxplot()+
  #ylim(0.8,3)+
  ylab("EdU Dense Ratio")+xlab("Dense Cells (FALSE)")+
  ggtitle(paste("EdU Intensity in Outer vs. Inner Cells\nin Extreme",extremePercent, "Percent Differential Response (True is Outer)"))+
  facet_wrap(~MEP, ncol = 10)+
  theme(strip.text = element_text(size = rel(.5)))
print(p)

kable(mDT, digits = 2, align = "l")

```

