---
output: html_document
---

---
title: "MEP-LINCS_PC3_Integrated_Analysis"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8,
                      echo=FALSE, warning=FALSE, message=FALSE)
```


```{r }
#Author: Mark Dane, copyright 2015

source("MEPLINCSFunctions.R")
  
#Set the cell line to be analyzed (PC3|MCF7|YAPC)
cellLine <- "PC3"


```




```{r setup}
library("ggplot2")
library("data.table")
library("MEMA")
library("grid")
library(knitr)
library("gplots")
library("RColorBrewer")


#Setup colors for Barcode and text in all heatmaps
selDark2 <- colorRampPalette(brewer.pal(8,"Dark2"))
plateCol = selDark2(8)
ligandTypeCols = selDark2(28)


combineSSs <- function(SSs){
  #browser()
  l4List <- lapply(SSs, function(ss){
    l4 <- fread(paste0("./",cellLine,"/",ss,"/AnnotatedData/",cellLine,"_",ss,"_Level4.txt"), showProgress = FALSE)
    setkey(l4,"ECMp")
    l4 <- l4[!"fiducial"]
    l4 <- l4[!"blank"]
    setkey(l4, "MEP")
    l4$SS <- ss
    return(l4)
  })
  
  l4SS1 <- l4List[[1]]
  l4SS2 <- l4List[[2]]
  l4SS3 <- l4List[[3]]
  
  cMEPs <- intersect(intersect(l4SS1$MEP,l4SS2$MEP),l4SS3$MEP)
  cMEPsnoFBS <- cMEPs[!grepl("FBS",cMEPs)]
  
  #Bind the no FBS data from the common MEPs
  DT <- data.table(l4SS1[l4SS1$MEP %in% cMEPsnoFBS], l4SS2[l4SS2$MEP %in% cMEPsnoFBS], l4SS3[l4SS3$MEP %in% cMEPsnoFBS], check.names = TRUE)
}


combineSSsFBS <- function(SSs){
  l4List <- lapply(SSs, function(ss){
    l4 <- fread(paste0("./",cellLine,"/",ss,"/AnnotatedData/",cellLine,"_",ss,"_Level4.txt"), showProgress = FALSE)
    setkey(l4,"Ligand")
    l4 <- l4["FBS"]
    setkey(l4,"ECMp")
    l4 <- l4[!"fiducial"]
    l4 <- l4[!"blank"]
    setkey(l4, "MEP")
    setnames(l4, colnames(l4), paste(ss,colnames(l4),sep="_"))
    l4$SS <- ss
    return(l4)
  })
  
  l4SS1 <- l4List[[1]]
  l4SS2 <- l4List[[2]]
  l4SS3 <- l4List[[3]]
  
  #Bind the FBS data from the common MEPs
  DT <- data.table(l4SS1, l4SS2, l4SS3)
}

```

```{r,fig.height= 3.5, fig.width=3.5, eval=TRUE}


DT <- combineSSsFBS(SSs = c("SS1","SS2","SS3"))[,list(SS1_MEP, SS1_Spot_PA_SpotCellCount,SS1_Spot_PA_SpotCellCount_MedNorm, SS2_Spot_PA_SpotCellCount,SS2_Spot_PA_SpotCellCount_MedNorm, SS3_Spot_PA_SpotCellCount,SS3_Spot_PA_SpotCellCount_MedNorm)]

setnames(DT, "SS1_MEP", "MEP")
DT <- DT[,lapply(.SD, numericMedian), by="MEP"]

#Show scattter plots of raw and normalized spot cell count in each ss
p <- ggplot(DT, aes(x = SS1_Spot_PA_SpotCellCount, y = SS2_Spot_PA_SpotCellCount))+
  geom_point(siz = rel(.4), alpha = .6)+
  stat_smooth(method = "loess", span = 1)+
  xlim(0,40)+ylim(0,40)+
  xlab("SS1 Spot Cell Count")+ylab("SS2 Spot Cell Count")+
  ggtitle("Spot Cell Count Across\nStaining Sets")+
  guides(colour=FALSE)+
  geom_text(x = 20, y = 35, label = lm_eqn(DT[,list(x=SS1_Spot_PA_SpotCellCount,  y=SS2_Spot_PA_SpotCellCount)]), parse = TRUE)
print(p)

p <- ggplot(DT, aes(x = SS1_Spot_PA_SpotCellCount_MedNorm, y = SS2_Spot_PA_SpotCellCount_MedNorm))+
  geom_point(siz = rel(.4), alpha = .6)+
  stat_smooth(method = "loess", span = 1)+
  xlim(0,1.5)+ylim(0,1.5)+
  xlab("SS1 Spot Cell Count")+ylab("SS2 Spot Cell Count")+
  ggtitle("Normalized Spot Cell Count\nAcross Staining Sets")+
  guides(colour=FALSE)+
  geom_text(x = .7, y = 1.2, label = lm_eqn(DT[,list(x=SS1_Spot_PA_SpotCellCount_MedNorm,  y=SS2_Spot_PA_SpotCellCount_MedNorm)]), parse = TRUE)
print(p)

p <- ggplot(DT, aes(x = SS1_Spot_PA_SpotCellCount, y = SS3_Spot_PA_SpotCellCount))+ 
  geom_point(siz = rel(.4), alpha = .6)+
  stat_smooth(method = "loess", span = 1)+
  xlim(0,40)+ylim(0,40)+
  xlab("SS1 Spot Cell Count")+ylab("SS3 Spot Cell Count")+
  ggtitle("Spot Cell Count \nAcross Staining Sets")+
  guides(colour=FALSE)+
  geom_text(x = 20, y = 35, label = lm_eqn(DT[,list(x=SS1_Spot_PA_SpotCellCount,  y=SS3_Spot_PA_SpotCellCount)]), parse = TRUE)
print(p)

p <- ggplot(DT, aes(x = SS1_Spot_PA_SpotCellCount_MedNorm, y = SS3_Spot_PA_SpotCellCount_MedNorm))+
  geom_point(siz = rel(.4), alpha = .6)+
  stat_smooth(method = "loess", span = 1)+
  xlim(0,1.5)+ylim(0,1.5)+
  xlab("SS1 Spot Cell Count")+ylab("SS3 Spot Cell Count")+
  ggtitle("Normalized Spot Cell Count \nAcross Staining Sets")+
  guides(colour=FALSE)+
  geom_text(x = .7, y = 1.2, label = lm_eqn(DT[,list(x=SS1_Spot_PA_SpotCellCount_MedNorm,  y=SS3_Spot_PA_SpotCellCount_MedNorm)]), parse = TRUE)
print(p)

p <- ggplot(DT, aes(x = SS2_Spot_PA_SpotCellCount, y = SS3_Spot_PA_SpotCellCount))+
  geom_point(siz = rel(.4), alpha = .6)+
  stat_smooth(method = "loess", span = 1)+
  xlim(0,40)+ylim(0,40)+
  xlab("SS2 Spot Cell Count")+ylab("SS3 Spot Cell Count")+
  ggtitle("Spot Cell Count \nAcross Staining Sets")+
  guides(colour=FALSE)+
  geom_text(x = 20, y = 35, label = lm_eqn(DT[,list(x=SS2_Spot_PA_SpotCellCount,  y=SS3_Spot_PA_SpotCellCount)]), parse = TRUE)
print(p)

p <- ggplot(DT, aes(x = SS2_Spot_PA_SpotCellCount_MedNorm, y = SS3_Spot_PA_SpotCellCount_MedNorm))+
  geom_point(siz = rel(.4), alpha = .6)+
  stat_smooth(method = "loess", span = 1)+
  xlim(0,1.5)+ylim(0,1.5)+
  xlab("SS2 Spot Cell Count")+ylab("SS3 Spot Cell Count")+
  ggtitle("Normalized Spot Cell Count \nAcross Staining Sets")+
  guides(colour=FALSE)+
  geom_text(x = .7, y = 1.2, label = lm_eqn(DT[,list(x=SS2_Spot_PA_SpotCellCount_MedNorm,  y=SS3_Spot_PA_SpotCellCount_MedNorm)]), parse = TRUE)
print(p)

```

```{r, fig.height=16}
#Create a data.table with MEP rows, feature vector and metadata columns
#MEP rows should be median normalized
#Metadata in columns should be ECMp, Ligand, MEP
#Start with curated feature vectors that are unique
#Maybe summarize common parameters such as DNA content
#

#Start with the full combined dataset, no FBS
#TODO: Add one row of FBS medians to show white

DT <- combineSSs(SSs = c("SS1","SS2","SS3"))

#Add a dummy values for ligand type
setkey(DT,Ligand)
DT$LigandType <- as.factor(toupper(substring(DT$Ligand, 1,2)))

#Build the feature set to keep
fullBio <- DT[,grep("MedNorm|MEP|Ligand|ECMp",colnames(DT), value=TRUE), with = FALSE]
#Delete repeated columns, keeping the first one only
#TODO: Take medians of parameters that are common across staining sets
#such as SpotCellCount, Area, perimeter, DNA4n
#Reduce to biologically likely relevant
fullBio <- fullBio[,grep("[.](1|2)|Cells|Cytoplasm.*Dapi|Cytoplasm.*Area|CellMask|Center|Nuclei.*KRT", colnames(fullBio), value = TRUE, invert = TRUE), with = FALSE]
#Reduce to biologically minimal choice
fullBio <- fullBio[,grep("Actin|Integrated|Dapi", colnames(fullBio), value = TRUE, invert = TRUE), with = FALSE]

# Minimize column names
fullBio <- setnames(fullBio,colnames(fullBio),gsub("_MedNorm|.*_CP_|.*_PA_|Intensity_|AreaShape_|Cycle_","",colnames(fullBio)))

m <- as.matrix(fullBio[,grep("Ligand|ECMp|MEP",x = colnames(fullBio), value = TRUE, invert = TRUE), with = FALSE])
rownames(m) <- fullBio$MEP

#Plot full bio heatmap
heatmap.2(m,scale="column", col = bluered, trace = "none", cexRow=.5, cexCol=.9, key=FALSE, main = paste("All Biological Features"), lmat=rbind(c(5,0,4,0),c(3,1,2,0)), lhei=c(2.0,5.0), lwid=c(1.5,0.2,2.5,2.5), mar=c(20,5), RowSideColors=ligandTypeCols[fullBio$LigandType], colRow = ligandTypeCols[fullBio$LigandType])

#Remove redundat features
reducedBio <- fullBio[,grep("Perimeter|4N|KRT|SpotCellCount|MedianEdu|H3", colnames(fullBio),value=TRUE, invert = TRUE),with=FALSE]

m <- as.matrix(reducedBio[,grep("Ligand|ECMp|MEP",x = colnames(reducedBio), value = TRUE, invert = TRUE), with = FALSE])
rownames(m) <- reducedBio$MEP

#Plot full bio heatmap
heatmap.2(m, col = bluered, scale = "column", trace = "none", cexRow=.5, cexCol=.9, key=FALSE, main = paste("PC3 Biological Features"), lmat=rbind(c(5,0,4,0),c(3,1,2,0)), lhei=c(2.0,5.0), lwid=c(1.5,0.2,2.5,2.5), mar=c(20,5), RowSideColors=ligandTypeCols[reducedBio$LigandType], colRow = ligandTypeCols[reducedBio$LigandType])

#Plot full bio heatmap
myBreaks = seq(0, 2, .05)
heatmap.2(m, col = bluered, breaks = myBreaks, trace = "none", cexRow=.5, cexCol=.9, key=FALSE, main = paste("PC3 Biological Features"), lmat=rbind(c(5,0,4,0),c(3,1,2,0)), lhei=c(2.0,5.0), lwid=c(1.5,0.2,2.5,2.5), mar=c(20,5), RowSideColors=ligandTypeCols[reducedBio$LigandType], colRow = ligandTypeCols[reducedBio$LigandType])
```


```{r,fig.height= 3.5, fig.width=3.5, eval=TRUE}


DT <- combineSSs(SSs = c("SS1","SS2","SS3"))

#Show scattter plots of raw and normalized spot cell count in each ss
p <- ggplot(DT, aes(x = SS1_Spot_PA_SpotCellCount, y = SS2_Spot_PA_SpotCellCount, colour=SS1_Barcode))+
  geom_point(siz = rel(.4), alpha = .6)+
  stat_smooth(method = "loess",se=FALSE)+
  xlim(0,40)+ylim(0,40)+
  xlab("SS1 Spot Cell Count")+ylab("SS2 Spot Cell Count")+
  ggtitle("Spot Cell Count Across\nStaining Sets")+
  guides(colour=FALSE)
print(p)

p <- ggplot(DT, aes(x = SS1_Spot_PA_SpotCellCount_MedNorm, y = SS2_Spot_PA_SpotCellCount_MedNorm, colour=SS1_Barcode))+
  geom_point(siz = rel(.4), alpha = .6)+
  stat_smooth(method = "loess",se=FALSE)+
  xlim(0,1.5)+ylim(0,1.5)+
  xlab("SS1 Spot Cell Count")+ylab("SS2 Spot Cell Count")+
  ggtitle("Normalized Spot Cell Count\nAcross Staining Sets")+
  guides(colour=FALSE)
print(p)

p <- ggplot(DT, aes(x = SS1_Spot_PA_SpotCellCount, y = SS3_Spot_PA_SpotCellCount, colour=SS1_Barcode))+ 
  geom_point(siz = rel(.4), alpha = .6)+
  stat_smooth(method = "loess",se=FALSE)+
  xlim(0,40)+ylim(0,40)+
  xlab("SS1 Spot Cell Count")+ylab("SS3 Spot Cell Count")+
  ggtitle("Spot Cell Count \nAcross Staining Sets")+
  guides(colour=FALSE)
print(p)

p <- ggplot(DT, aes(x = SS1_Spot_PA_SpotCellCount_MedNorm, y = SS3_Spot_PA_SpotCellCount_MedNorm, colour=SS1_Barcode))+
  geom_point(siz = rel(.4), alpha = .6)+
  stat_smooth(method = "loess",se=FALSE)+
  xlim(0,1.5)+ylim(0,1.5)+
  xlab("SS1 Spot Cell Count")+ylab("SS3 Spot Cell Count")+
  ggtitle("Normalized Spot Cell Count \nAcross Staining Sets")+
  guides(colour=FALSE)
print(p)

p <- ggplot(DT, aes(x = SS2_Spot_PA_SpotCellCount, y = SS3_Spot_PA_SpotCellCount, colour=SS1_Barcode))+
  geom_point(siz = rel(.4), alpha = .6)+
  stat_smooth(method = "loess",se=FALSE)+
  xlim(0,40)+ylim(0,40)+
  xlab("SS2 Spot Cell Count")+ylab("SS3 Spot Cell Count")+
  ggtitle("Spot Cell Count \nAcross Staining Sets")+
  guides(colour=FALSE)
print(p)

p <- ggplot(DT, aes(x = SS2_Spot_PA_SpotCellCount_MedNorm, y = SS3_Spot_PA_SpotCellCount_MedNorm, colour=SS1_Barcode))+
  geom_point(siz = rel(.4), alpha = .6)+
  stat_smooth(method = "loess",se=FALSE)+
  xlim(0,1.5)+ylim(0,1.5)+
  xlab("SS2 Spot Cell Count")+ylab("SS3 Spot Cell Count")+
  ggtitle("Normalized Spot Cell Count \nAcross Staining Sets")+
  guides(colour=FALSE)
print(p)

```
