---
title: "MCF10A Cell Titrate 96"
author: "Mark Dane"
date: "3/16/2017"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
    source_code: embed
---



```{r "setup", include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8,
                      echo=FALSE, warning=FALSE, message=FALSE, cache=FALSE)

#Author: Mark Dane, copyright 2015-2017

library(MEMA)
library(ggplot2)
library(stringr)
library(scales)


path <- "/lincs/share/lincs_user/study"
studyName <- "MCF10A_Cell_Titrate_96"

```


```{r readWriteLevel3and4Data, echo=FALSE}

l3 <- fread(paste0(path,"/",studyName,"/Annotated/",studyName,"_Level3.tsv"),verbose = FALSE, showProgress = FALSE)
l4 <- fread(paste0(path,"/",studyName,"/Annotated/",studyName,"_Level4.tsv"),verbose = FALSE, showProgress = FALSE)

```

###Experiment Overview

```{r cellCountLayout, fig.width=12,fig.height=8}

dt <- unique(l3[,.(Well, Ligand, Barcode, ECMp, PlatingDensity, Spot_PA_SpotCellCount, ArrayRow, ArrayColumn)])
dt$Well_Ligand <-paste(dt$Well,dt$Ligand,sep="_")
dt$WellRow <- factor(gsub("[[:digit:]]*","",dt$Well),levels = c("H","G","F","E","D","C","B","A"))
dt$WellCol <- as.integer(gsub("[[:alpha:]]","",dt$Well))

p <- ggplot(l3, aes(x=ArrayColumn, y=ArrayRow, colour=Spot_PA_SpotCellCount))+
  geom_point(size=rel(2))+
  scale_y_reverse()+
  scale_x_continuous(breaks= c(min(l3$ArrayColumn),round(mean(c(min(l3$ArrayColumn),max(l3$ArrayColumn)))),max(l3$ArrayColumn)))+
  scale_colour_gradient(low = "white", high = "red")+
  guides(colour = guide_legend("Spot Cell Count", keywidth = .5, keyheight = .5))+
  ggtitle(paste("Spot Cell Count for",unique(l3$CellLine), "cells in plate",unique(l3$Barcode)))+
  xlab("")+ylab("")+theme(axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=1, size=rel(.8)),axis.title.x = element_text(size=rel(1)),plot.title = element_text(size = rel(1)),legend.text=element_text(size = rel(1)),legend.title=element_text(size = rel(1)), strip.text = element_text(size = 5))+
  facet_wrap(~Well, ncol=12)
 p
 
 dt <- l3[grepl("COL1",ECMp),.(Spot_PA_SpotCellCount,Well,PlatingDensity,ECMp, Well)]
dt$WellCol <- as.integer(gsub("[[:alpha:]]","",dt$Well))
dt <- dt[,WellCellCount := sum(Spot_PA_SpotCellCount),by="Well"]
dt <- unique(dt[,Spot_PA_SpotCellCount :=NULL])
p <- ggplot(dt, aes(x=as.factor(PlatingDensity), y=WellCellCount))+
 geom_boxplot(fill="transparent", outlier.colour = NA, alpha=.5)+
  labs(x="Plating Density",
       y="Well Cell Count",
       title="Well Cell Count at Different Plating Densities")+
theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size=rel(.7)), axis.text.y = element_text(angle = 0, vjust = 0.5, hjust=1, size=rel(1)), plot.title = element_text(size = rel(1)),legend.text=element_text(size = rel(1)),legend.title=element_text(size = rel(1)))
p <- p +  geom_jitter(aes(),size=rel(1),alpha=.5)
p

dt <- unique(l3[,.(Well, Ligand, Barcode, ECMp, PlatingDensity, Spot_PA_SpotCellCount, ArrayRow, ArrayColumn)])
dt$WellRow <- factor(gsub("[[:digit:]]*","",dt$Well),levels = c("H","G","F","E","D","C","B","A"))
dt$WellCol <- as.integer(gsub("[[:alpha:]]","",dt$Well))
p <- ggplot(dt, aes(x =WellCol, y=WellRow, colour=log2(PlatingDensity), label=factor(PlatingDensity)))+
  geom_point(size=15)+
  geom_text(colour="white")+
  guides(colour=FALSE)+
   scale_x_continuous(breaks= scales::pretty_breaks())+
  labs(x="Well Column", y="Well Row",title="Cells Plated in Each Well")
p
```


***
This experiment used `r length(unique(l3$Barcode))` `r length(unique(l3$Well))` well plates.

###Normalized Cell Counts

```{r normCellCounts}

dt <- l3[grepl("COL1",ECMp),.(Spot_PA_SpotCellCount,Well,PlatingDensity,ECMp, Well, Block)]
dt$WellCol <- as.integer(gsub("[[:alpha:]]","",dt$Well))
dt$WellRow <- factor(gsub("[[:digit:]]*","",dt$Well),levels = c("H","G","F","E","D","C","B","A"))
dt <- dt[,WellCellCount := sum(Spot_PA_SpotCellCount),by="Well"]
dt <- dt[,WellCellCountNorm := medianNorm(WellCellCount), by="PlatingDensity"]
dt <- unique(dt[,Spot_PA_SpotCellCount :=NULL])

p <- ggplot(dt, aes(x=WellCol, y=WellCellCountNorm, colour=as.factor(PlatingDensity)))+
  geom_point()+
  stat_smooth(span=1, se=FALSE)+
  scale_x_continuous(breaks= scales::pretty_breaks())+
  labs(x="Plate Column",y="Cell Count", title="Cell Counts Normalized to Plating Density Across the Plate",colour="Plating Density\n(Cells/Well)")
p


p <- ggplot(dt, aes(x=as.integer(WellRow), y=WellCellCountNorm, colour=as.factor(WellCol)))+
  geom_point()+
  stat_smooth(span=1, se=FALSE)+
  labs(x="Plate Row",y="Normalized Cell Count", title="Cell Counts Normalized to Plating Density Down the Plate",colour="Well Column")
p

p <- ggplot(dt, aes(x=as.factor(Block), y=WellCellCountNorm, colour=as.factor(WellCol)))+
  geom_boxplot()+
  labs(x="Print Pin",y="Normalized Cell Count", title="Cell Counts Normalized to Plating Density By Printhead Pin",colour="Well Column")
p <- p +  geom_jitter(aes(colour=as.factor(WellCol)),size=rel(1),alpha=.5)

p



```

***
The well cell counts are divided by the median well cell count of all wells with the same plating density. This allows comparing the variation in cell counts across and down the plate.  

###Coefficients of Variation


```{r CVs}
#Calculate CVs for each well
dt <- l3[grepl("COL1",ECMp),.(Spot_PA_SpotCellCount,Well,PlatingDensity,ECMp,Block)]
dt$WellRow <- factor(gsub("[[:digit:]]*","",dt$Well),levels = c("H","G","F","E","D","C","B","A"))
dt$WellCol <- as.integer(gsub("[[:alpha:]]","",dt$Well))
dt <- dt[,SCC_CV := MEMA:::CV(Spot_PA_SpotCellCount),by=Well]
dt <- unique(dt[,Spot_PA_SpotCellCount :=NULL])

p <- ggplot(dt, aes(x=WellCol, y=SCC_CV, colour=as.factor(PlatingDensity)))+
  geom_point()+
  stat_smooth(span=1, se=FALSE)+
  scale_x_continuous(breaks= scales::pretty_breaks())+
  labs(x="Plate Column",y="Cell Count CV", title="Coefficients of Variation Across the Plate\nat different Plating Densities",colour="Plating Density\n(Cells/Well)")
p

p <- ggplot(dt, aes(x=as.factor(Block), y=SCC_CV, colour=as.factor(WellCol)))+
  geom_boxplot()+
  labs(x="Print Pin",y="Cell Count CV", title="Coefficients of Variation Grouped by Pin\n and Plate Column",colour="Column")
p <- p +  geom_jitter(aes(colour=as.factor(WellCol)),size=rel(1),alpha=.5)
p

```

***
