
```{r "setup", include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8,
                      echo=FALSE, warning=FALSE, message=FALSE, cache=FALSE)
knitr::opts_knit$set(root.dir = "/data/share/dane/MEP-LINCS/MEP_LINCS/archive")

#Author: Mark Dane, copyright 2017

library("ggplot2")
library("data.table")
library("MEMA")
library("knitr")
library(synapseClient)
suppressMessages(synapseLogin())
library(plotly)

reAnnotatedDir <- "syn5706203"
preAnnotatedDir <- "syn5713302"

q <- sprintf("select  id,name,Level,StainingSet,Study,Preprocess from entity WHERE parentId =='%s' AND Level != '1' AND Level != '2' AND Level != 1", reAnnotatedDir)
reFiles <- data.table(synQuery(q))

q <- sprintf("select id,name,Level,StainingSet,Study,Preprocess from entity WHERE parentId =='%s' AND Level != '1' AND Level != '2' ", preAnnotatedDir)
preFiles <- data.table(synQuery(q))

#Define a study to compare signals in released and prerlease datasets
studyName <- "hmec122l_ss4"

# Download files, or get from cache if already downloaded
reL4 <- lapply(reFiles$entity.id[tolower(reFiles$entity.Study)==studyName&reFiles$entity.Level=='4'], synGet)
preL4 <- lapply(preFiles$entity.id[tolower(preFiles$entity.Study)==studyName&preFiles$entity.Level=='4'], synGet)

# Get the path on disk to each file
reL4FilePath <- unlist(lapply(reL4, getFileLocation))
preL4FilePath <- unlist(lapply(preL4, getFileLocation))

reL4 <-  fread(reL4FilePath, verbose = FALSE, showProgress = FALSE)
reL4$Version <- "av1.7"
preL4 <-  fread(preL4FilePath, verbose = FALSE, showProgress = FALSE)
preL4$Version <- "v1.8"

#Change the names of signals to be compared to easily ID
reL4$Spot_PA_SpotCellCountNorm_Release <- 2^reL4$Spot_PA_SpotCellCountLog2RUVLoess
setnames(preL4, "Spot_PA_SpotCellCountNorm", "Spot_PA_SpotCellCountNorm_Prelease")
reL4$Nuclei_PA_Gated_EdUPositiveProportionNorm_Release <- plogis(reL4$Nuclei_PA_Gated_EdUPositiveProportionLogitRUVLoess)
setnames(preL4, "Nuclei_PA_Gated_EdUPositiveProportionNorm", "Nuclei_PA_Gated_EdUPositiveProportionNorm_Prelease")

l4C <- merge(reL4, preL4, by="MEP")

```


```{r readLevel3, echo=FALSE}

# Download files, or get from cache if already downloaded
reL3 <- lapply(reFiles$entity.id[tolower(reFiles$entity.Study)==studyName&reFiles$entity.Level=='3'], synGet)
preL3 <- lapply(preFiles$entity.id[tolower(preFiles$entity.Study)==studyName&preFiles$entity.Level=='3'], synGet)

# Get the path on disk to each file
reL3FilePath <- unlist(lapply(reL3, getFileLocation))
preL3FilePath <- unlist(lapply(preL3, getFileLocation))

reL3 <-  fread(reL3FilePath, verbose = FALSE, showProgress = FALSE)
reL3$Version <- "av1.7"
preL3 <-  fread(preL3FilePath, verbose = FALSE, showProgress = FALSE)
preL3$Version <- "v1.8"

#Change the names of signals to be compared to easily ID
reL3$Spot_PA_SpotCellCountNorm_Release <- 2^reL3$Spot_PA_SpotCellCountLog2RUVLoess
setnames(preL3, "Spot_PA_SpotCellCountNorm", "Spot_PA_SpotCellCountNorm_Prelease")
reL3$Nuclei_PA_Gated_EdUPositiveProportionNorm_Release <- plogis(reL3$Nuclei_PA_Gated_EdUPositiveProportionLogitRUVLoess)
setnames(preL3, "Nuclei_PA_Gated_EdUPositiveProportionNorm", "Nuclei_PA_Gated_EdUPositiveProportionNorm_Prelease")

l3C <- merge(reL3, preL3, by=c("Barcode","Well","Spot"))
reL3$BWS <- paste(reL3$Barcode,reL3$Well,reL3$Spot,sep="_")
preL3$BWS <- paste(preL3$Barcode,preL3$Well,preL3$Spot,sep="_")

l3C <- l3C[,WellRow := gsub("[[:digit:]]*","",Well)]

```

###`r studyName` Spot Cell Count Comparisons


```{r SCCScatterplots}


p <- ggplot(l3C, aes(x=Spot_PA_SpotCellCount.x, y=Spot_PA_SpotCellCount.y, label=MEP.x))+
  geom_point()+
  labs(x="Release Spot Cell Count",
       y="Prerelease Spot Cell Count",
       title="Level 3 Spot Cell Count Comparisons")
p

p <- ggplot(l3C, aes(x=Spot_PA_SpotCellCountNorm_Release, y=Spot_PA_SpotCellCountNorm_Prelease, colour=WellRow))+
  geom_point(alpha=.5)+
  labs(x="Release Normalized Spot Cell Count",
       y="Prerelease Normalized Spot Cell Count",
       title="Level 3 Normalized Spot Cell Count Comparisons")
print(p)

# p <- ggplot(preL3, aes(x=Spot_PA_SpotCellCount, y=Spot_PA_SpotCellCountNorm_Prelease))+
#   geom_point(alpha=.5)+
#   stat_smooth()+
#   labs(x="Prerelease Spot Cell Count",
#        y="Prerelease Normalized Spot Cell Count",
#        title="Level 3 Normalized Spot Cell Count Comparisons")
# print(p)

p <- ggplot(l4C, aes(x=Spot_PA_SpotCellCount.x, y=Spot_PA_SpotCellCount.y, label=MEP))+
  geom_point()+
  labs(x="Release Spot Cell Count",
       y="Prerelease Spot Cell Count",
       title="Level 4 Spot Cell Count Comparisons")
ggplotly(p)

p <- ggplot(l4C, aes(x=Spot_PA_SpotCellCountNorm_Release, y=Spot_PA_SpotCellCountNorm_Prelease, colour=Barcode.x))+
  geom_point(alpha=.4)+
  labs(x="Release Normalized Spot Cell Count",
       y="Prerelease Normalized Spot Cell Count",
       title="Level 4 Normalized Spot Cell Count Comparisons")

print(p)

```


###`r studyName` Gated Value Comparisons


```{r DNA2nScatterplots}
p <- ggplot(l3C, aes(x=Nuclei_PA_Cycle_DNA2NProportion.x, y=Nuclei_PA_Cycle_DNA2NProportion.y, label=MEP.x))+
  geom_point()+
  labs(x="Release DNA 2n Proportion",
       y="Prerelease DNA 2n Proportion",
       title="Level 3  DNA 2n Proportion (Two different autogating algorithms")
p

if("Nuclei_PA_Gated_EdUPositiveProportion.x" %in% colnames(l3C)){
  p <- ggplot(l3C, aes(x=Nuclei_PA_Gated_EdUPositiveProportion.x, y=Nuclei_PA_Gated_EdUPositiveProportion.x, label=MEP.x))+
  geom_point()+
  labs(x="Release EdU Positive Gated Proportion",
       y="Prerelease EdU Positive Gated Proportion",
       title="Level 3 EdU Positive Gated Proportion")
p

p <- ggplot(l3C, aes(x=Nuclei_PA_Gated_EdUPositiveProportionNorm_Release, y=Nuclei_PA_Gated_EdUPositiveProportionNorm_Prelease, colour=WellRow))+
  geom_point(alpha=.5)+
  labs(x="Release Normalized EdU Positive Gated Proportion",
       y="Prerelease Normalized EdU Positive Gated Proportion",
       title="Level 3 Normalized EdU Positive Gated Proportion")
print(p)

p <- ggplot(l4C, aes(x=Nuclei_PA_Gated_EdUPositiveProportionNorm_Release, y=Nuclei_PA_Gated_EdUPositiveProportionNorm_Prelease, colour=Barcode.x))+
  geom_point(alpha=.4)+
  labs(x="Release Normalized EdU Positive Gated Proportion",
       y="Prerelease Normalized EdU Positive Gated Proportion",
       title="Level 4 Normalized EdU Positive Gated Proportion")

p
}

```

