---
title: "MCF10A Collagen Attach and Growth"
author: "Mark Dane"
date: "`r Sys.Date()`"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
    source_code: embed
---



```{r "setup", include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8,
                      echo=FALSE, warning=FALSE, message=FALSE, cache=FALSE)

#Author: Mark Dane, copyright 2015-2017

library(MEMA)
library(ggplot2)
library(stringr)
library(scales)


path <- "/lincs/share/lincs_user/incell96well/study"
studyNameA <- "MCF10A_Collagen_Attach"
studyNameG <- "MCF10A_Collagen_Growth"

```


```{r readWriteLevel3and4Data, echo=FALSE}

l3A <- fread(paste0(path,"/",studyNameA,"/Annotated/",studyNameA,"_Level3.tsv"),verbose = FALSE, showProgress = FALSE)
l3A$Time <- "T16"
l3A <- l3A[,Spot_PA_ReplicateCount :=NULL]
l3A <- l3A[!grepl("gelatin",l3A$ECMp),]
l3A <- l3A[!l3A$ECMp=="",]
l3G <- fread(paste0(path,"/",studyNameG,"/Annotated/",studyNameG,"_Level3.tsv"),verbose = FALSE, showProgress = FALSE)
l3G$Time <- "T0"
l3G <- l3G[!grepl("gelatin",l3G$ECMp),]
l3G <- l3G[!l3G$ECMp=="",]
l3G$Time[l3G$Barcode=="LI9V01702"] <- "T72"

l3 <- rbind(l3A,l3G)
l3$PBSBase <- "Collagen"
l3$PBSBase[grepl("PBS",l3$ECMp)] <- "PBS"

```

###Experiment Overview

```{r cellCountLayout, fig.width=12,fig.height=8}


# p <- ggplot(l3, aes(x=ArrayColumn, y=ArrayRow, colour=Spot_PA_SpotCellCount))+
#   geom_point(size=rel(2))+
#   scale_y_reverse()+
#   scale_x_continuous(breaks= c(min(l3$ArrayColumn),round(mean(c(min(l3$ArrayColumn),max(l3$ArrayColumn)))),max(l3$ArrayColumn)))+
#   scale_colour_gradient(low = "white", high = "red")+
#   guides(colour = guide_legend("Spot Cell Count")+
#   ggtitle(paste("Spot Cell Count for",unique(l3$CellLine), "cells in plate",unique(l3$Barcode)))+
#   xlab("")+ylab("")+theme(axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=1, size=rel(.8)),axis.title.x = element_text(size=rel(1)),plot.title = element_text(size = rel(1)),legend.text=element_text(size = rel(1)),legend.title=element_text(size = rel(1)), strip.text = element_text(size = 5))+
#   facet_wrap(~Well, ncol=4)
#  p
#  

dt <- unique(l3A[,.(Well, Ligand, Barcode, ECMp, Spot_PA_SpotCellCount, CellLine)])
dt$Well_Ligand <-paste(dt$Well,dt$Ligand,sep="_")
dt$WellRow <- factor(gsub("[[:digit:]]*","",dt$Well),levels = c("H","G","F","E","D","C","B","A"))
dt$WellCol <- as.integer(gsub("[[:alpha:]]","",dt$Well))

 p <- ggplot(dt, aes(x=ECMp, y=Spot_PA_SpotCellCount))+
 geom_boxplot(fill="transparent", outlier.colour = NA, alpha=.5)+
  guides(colour = guide_legend("Spot Cell Count"))+
  labs(x = "ECM Protein", y="Spot Cell Count",title=paste("Spot Cell Counts After Overnight for",unique(dt$CellLine), "cells in plate",unique(dt$Barcode)))+
 theme(axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=1, size=rel(.8)),axis.title.x = element_text(size=rel(1)),plot.title = element_text(size = rel(1)),legend.text=element_text(size = rel(1)),legend.title=element_text(size = rel(1)), strip.text = element_text(size = 5))
 p <- p +  geom_jitter(aes(),size=rel(.1),alpha=.2)

 p
 
 dt <- unique(l3G[,.(Well, Ligand, Barcode, ECMp, Time, Spot_PA_SpotCellCount, CellLine)])
dt$Well_Ligand <-paste(dt$Well,dt$Ligand,sep="_")
dt$WellRow <- factor(gsub("[[:digit:]]*","",dt$Well),levels = c("H","G","F","E","D","C","B","A"))
dt$WellCol <- as.integer(gsub("[[:alpha:]]","",dt$Well))

 p <- ggplot(dt, aes(x=ECMp, y=Spot_PA_SpotCellCount))+
 geom_boxplot(fill="transparent", outlier.colour = NA, alpha=.5)+
  guides(colour = guide_legend("Spot Cell Count"))+
  labs(x = "ECM Protein", y="Spot Cell Count",title=paste("Spot Cell Count After Growth for",unique(dt$CellLine), "cells at Time 0 and 72 hours"))+
 theme(axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=1, size=rel(.8)),axis.title.x = element_text(size=rel(1)),plot.title = element_text(size = rel(1)),legend.text=element_text(size = rel(1)),legend.title=element_text(size = rel(1)), strip.text = element_text(size = 10))+
   facet_wrap(~Time)
 p <- p +  geom_jitter(aes(),size=rel(.1),alpha=.2)

 p
 
  p <- ggplot(l3, aes(x=ECMp, y=Spot_PA_SpotCellCount, colour=factor(Time)))+
 geom_boxplot(fill="transparent", outlier.colour = NA, alpha=.5)+
  guides(colour = guide_legend("Time"))+
  labs(x = "ECM Protein", y="Spot Cell Count",title=paste("Spot Cell Count for",unique(l3$CellLine), "cells"))+
 theme(axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=1, size=rel(.8)),axis.title.x = element_text(size=rel(1)),plot.title = element_text(size = rel(1)),legend.text=element_text(size = rel(1)),legend.title=element_text(size = rel(1)), strip.text = element_text(size = 5))

 p
 
   p <- ggplot(l3, aes(x=factor(Time), y=Spot_PA_SpotCellCount, colour=factor(ECMp)))+
 geom_boxplot(fill="transparent", outlier.colour = NA, alpha=.5)+
  guides(colour = guide_legend("ECMp"))+
  labs(x = "Incubation Time", y="Spot Cell Count",title=paste("Spot Cell Count for",unique(l3$CellLine), "cells"))+
 theme(axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=1, size=rel(.8)),axis.title.x = element_text(size=rel(1)),plot.title = element_text(size = rel(1)),legend.text=element_text(size = rel(1)),legend.title=element_text(size = rel(1)), strip.text = element_text(size = 5))

 p
 
    p <- ggplot(l3, aes(x=factor(PBSBase), y=Spot_PA_SpotCellCount, colour=factor(ECMp)))+
 geom_boxplot(fill="transparent", outlier.colour = NA, alpha=.5)+
  guides(colour = guide_legend("ECMp"))+
  labs(x = "Base ECM Protein", y="Spot Cell Count",title=paste("Spot Cell Count for",unique(l3$CellLine), "cells"))+
 theme(axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=1, size=rel(.8)),axis.title.x = element_text(size=rel(1)),plot.title = element_text(size = rel(1)),legend.text=element_text(size = rel(1)),legend.title=element_text(size = rel(1)), strip.text = element_text(size = 10))+
      facet_wrap(~Time)

 p
 
```

***
