---
title: "HMEC240L tSNE Analysis"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    source_code: embed
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(readr)
library(ggplot2)
library(plotly)
library(reshape2)
library(d3heatmap)
library(Rtsne)

dfZoom <- function(x, min=.02, max=1){
  minMax <- quantile(unlist(x), probs=c(min,max), na.rm=TRUE)
  cl <- t(apply(x,1, function(c){
    c[c<minMax[1]] <- minMax[1]
    c[c>minMax[2]] <- minMax[2]
    return(c)
  }))
  return(data.frame(cl))
}

df <- read_tsv("./Data/HMEC240L_SSC_Level4.txt")
l4C <- df
df <- df[grep("Cytoplasm_PA_Gated_KRT19PositiveProportionLogitRUVLoess|EdUPositiveProportionLogitRUVLoess$|Spot_PA_SpotCellCountLog2$|MEP|ECMp$|^Ligand$",colnames(df), value=TRUE)]
df$Nuclei_PA_Gated_EdUPositiveProportionRUVLoess <- plogis(df$Nuclei_PA_Gated_EdUPositiveProportionLogitRUVLoess)
df$Cytoplasm_PA_Gated_KRT19PositiveProportionRUVLoess <- plogis(df$Cytoplasm_PA_Gated_KRT19PositiveProportionLogitRUVLoess)
df$Spot_PA_SpotCellCount <- 2^df$Spot_PA_SpotCellCountLog2

#Need to remove FBS entries that are duplicated after normalization
RUVLoessMEPNames <- grep("LoessRUV",grep("Log2RUVLoess$|LogitRUVLoess$",colnames(l4C), value=TRUE), value=TRUE, invert=TRUE)
l4C$Ligand <- sub("FBS.*","FBS",l4C$Ligand)
l4C$MEP <- sub("FBS.*","FBS",l4C$MEP)
l4CU <- unique(l4C)
data_matrix <- scale(as.matrix(l4CU[,RUVLoessMEPNames]))

set.seed(1234)
data_tsne <- Rtsne(data_matrix, perplexity = 15,check_duplicates = FALSE)
l4CU <- cbind(l4CU,data_tsne$Y)


hmcols<-colorRampPalette(c("blue","white","red"))(16)

```




```{r}
# Reactive that returns the whole dataset if there is no brush
selectedData <- reactive({
  data <- brushedPoints(df, input$hist_brush, yvar="Cytoplasm_PA_Gated_KRT19PositiveProportionRUVLoess",allRows = TRUE)
  if(!input$include) data <- data[!data$selected_,]
  else   data <- data[data$selected_,]
  if (nrow(data) == 0)
    data <- df
  data
})
```

Column {data-width=500}
-----------------------------------------------------------------------

###  {data-width=450}


```{r, fig.height=1}
checkboxInput("include", "Include Selected", value = TRUE)
```


### KRT19 High Histogram {data-width=450}

```{r}

plotOutput("hist", brush = brushOpts(id = "hist_brush"))
output$hist <- renderPlot({
  ggplot(df, aes(Cytoplasm_PA_Gated_KRT19PositiveProportionRUVLoess)) + geom_histogram(binwidth = .001)+
    labs(x="KRT19 High Proportion")+
   theme(axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=1, size=rel(.8)),
          axis.title.x = element_text(size=rel(1)),
          plot.title = element_text(size = rel(.8)),
          strip.text = element_text(size = rel(.5)),
          legend.text=element_text(size = rel(.4)),legend.title=element_text(size = rel(.3)))
})
```


### KRT19 High and Ligands {data-width=450}

```{r}
renderPlot({
  ggplot(selectedData(), aes(factor(Ligand), Cytoplasm_PA_Gated_KRT19PositiveProportionRUVLoess))  + geom_boxplot()+
      labs(x="Ligand", y="KRT19 High\nProportion")+
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size=rel(.8)),
          axis.title.x = element_text(size=rel(1)),
          plot.title = element_text(size = rel(.8)),
          strip.text = element_text(size = rel(.5)),
          legend.text=element_text(size = rel(.4)),legend.title=element_text(size = rel(.3)))

})
```



### KRT19 High and ECM Proteins {data-width=450}

```{r}
renderPlot({
  ggplot(selectedData(), aes(factor(ECMp), Cytoplasm_PA_Gated_KRT19PositiveProportionRUVLoess))  + geom_boxplot()+
      labs(x="ECM Protein", y="KRT19 High\nProportion")+
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size=rel(.8)),
          axis.title.x = element_text(size=rel(1)),
          plot.title = element_text(size = rel(.8)),
          strip.text = element_text(size = rel(.5)),
          legend.text=element_text(size = rel(.4)),legend.title=element_text(size = rel(.3)))

})
```


Column {data-width=500}
-----------------------------------------------------------------------


### KRT19 High vs. Spot Cell Count {data-width=450}



###tSNE plot of all MEP Signals by Ligand

```{r}
renderPlotly({

ggplot(l4CU, aes(x="1", y="2", colour=Ligand, text=paste("ECMp:",ECMp)))+
      geom_point(size = rel(.8), alpha = .6) +
  ggtitle(paste("tSNE plot of MEPs Coloured by Ligand"))+
  guides(colour = FALSE)
})
```


### KRT19 High Heat Map {data-width=450}

```{r Heatmap}

renderD3heatmap({
#Cast to get ligands into columns
dfc <- dcast(selectedData()[c("ECMp","Ligand","Cytoplasm_PA_Gated_KRT19PositiveProportionRUVLoess")],ECMp~Ligand, value.var = "Cytoplasm_PA_Gated_KRT19PositiveProportionRUVLoess")

rownames(dfc) <- dfc$ECMp
dfc <- dfc[,!grepl("ECMp",names(dfc))]
d3heatmap(dfZoom(dfc, .05, .95), xaxis_font_size="5pt", colors=hmcols, yaxis_font_size="4pt",Rowv = FALSE, Colv=FALSE)

})

```

