
```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8,
                      echo=FALSE, warning=FALSE, message=FALSE, cache=FALSE)

```


```{r, cache=FALSE}
#Author: Mark Dane, copyright 2015

source("MEPLINCSFunctions.R")

```



```{r setup,cache=FALSE}
library("ggplot2")
library("data.table")
library("MEMA")
library("grid")
library("knitr")
library("gplots")
library("RColorBrewer")
library(DT)
library(d3heatmap)
library(plotly)

cellLine <- "HMEC122L"
ss <- "SS0"
drug<- "none"
rawDataVersion <- "v2"
analysisVersion <- "av1.6"
```

```{r readData}

l3 <- fread(paste0("../AnnotatedData/",cellLine, "_",ss,"_",drug,"_",rawDataVersion,"_",analysisVersion,"_Level3.txt"), showProgress = FALSE)
l3$ECMp <- sub("hyaluronic_acid","HA",l3$ECMp)
l3$ECMp <- sub("_greater_than_",">",l3$ECMp)
l3$ECMp <- sub("_less_than_","<",l3$ECMp)
l3$ECMp <- sub("_.*","",l3$ECMp)
l3$MEP <- paste0(l3$ECMp,"_",l3$Ligand)

```


#MEP-LINCS HMEC 122L Control Plate Analysis
####date: `r Sys.Date()`

The settling time during cell plating was 35 minutes and the cell densities from wells B01 to B04 were 100K/well, 150K/well, 200K/well and 250K/well.  

<br>
```{r SCCHist, fig.height=4}

p <- ggplot(l3, aes(x=Spot_PA_SpotCellCount))+
  geom_histogram(binwidth = 2)+
  xlab("Spot Cell Count")+
  ggtitle(paste("Histogram of",unique(l3$CellLine),"Spot Cell Count by Well for plate",unique(l3$Barcode)))+
  facet_wrap(~Well, nrow=1)

print(p)

```

<br>

```{r ECMBoxPlots}

l3$OmeroDetailURL <- paste0('<a href="https://meplincs.ohsu.edu/webclient/img_detail/',l3$ImageID,'/"',' target="_blank">Omero</a>')

p <- ggplot(l3, aes(x=factor(ECMp), y=Spot_PA_SpotCellCount))+
  geom_boxplot()+
  xlab("Spot Cell Count")+
  ggtitle(paste(unique(l3$CellLine),"Spot Cell Count by ECM Protein and Well for plate",unique(l3$Barcode)))+
  facet_wrap(~Well, ncol=1)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0, hjust=0.5, size=rel(1)), axis.text.y = element_text(angle = 0, vjust = 0.5, hjust=1, size=rel(1)), plot.title = element_text(size = rel(1)),legend.text=element_text(size = rel(.3)),legend.title=element_text(size = rel(.3)))
p <- p + geom_hline(yintercept = median(l3$Spot_PA_SpotCellCount), colour="blue", alpha=.5)

print(p)

```

```{r datatable, cache=FALSE}

colNames <- c("ECMp","Well","ArrayRow", "ArrayColumn", "Spot_PA_SpotCellCount", "OmeroDetailURL")
colNamesDisplay <- c("ECMp","Well","ArrayRow", "ArrayColumn", "Spot Cell Count", "Image")

l3 <- setorder(l3,Spot_PA_SpotCellCount)
datatable(format(l3[, colNames, with=FALSE], digits=3, scientific = FALSE, nsmall=0), options = list(pageLength = 5), colnames = colNamesDisplay, escape=FALSE)
```