---
title: "Pin Analysis Study"
author: "Mark Dane"
date: "2/3/2017"
output: html_document
---

```{r "setup", include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8,
                      echo=FALSE, warning=FALSE, message=FALSE, cache=FALSE)
knitr::opts_knit$set(root.dir = "/graylab/share/dane/MEP-LINCS/MEP_LINCS/Release")

library("ggplot2")
library("data.table")
library("MEMA")
library("grid")
library("knitr")
library("gplots")
library("RColorBrewer")
library(DT)
library(d3heatmap)
library(plotly)

#Setup colors for Barcode and text in all heatmaps
selDark2 <- colorRampPalette(brewer.pal(8,"Dark2"))
plateCol = selDark2(8)
hmcols<-colorRampPalette(c("blue","white","red"))(16)
```


```{r readLevel3and4Data, echo=FALSE}
path <- "/lincs/share/lincs_user"
datasetName <- "Pin_Analysis_Study"
l3 <- fread(paste0(path,"/study/",datasetName,"/Annotated/",datasetName,"_Level3.tsv"),verbose = FALSE, showProgress = FALSE)
l4 <- fread(paste0(path,"/study/",datasetName,"/Annotated/",datasetName,"_Level4.tsv"),verbose = FALSE, showProgress = FALSE)

annotations <- fread(paste0(path,"/study/",datasetName,"/Annotated/",datasetName,"_Level3Annotations.tsv"),header = FALSE)
CellLine = annotations$V2[annotations$V1=="CellLine"]
Preprocess = annotations$V2[annotations$V1=="Preprocess"]
DataType = annotations$V2[annotations$V1=="DataType"]
Consortia = annotations$V2[annotations$V1=="Consortia"]
Drug = annotations$V2[annotations$V1=="Drug"]
Segmentation = annotations$V2[annotations$V1=="Segmentation"]
StainingSet = annotations$V2[annotations$V1=="StainingSet"]
Level = annotations$V2[annotations$V1=="Level"]


barcodes <- sort(unique(l3$Barcode))

#Set a threshold for filtering wells on their QA score
wellQAThresh <- 0.7

#TODO: Read this from Level 3 data
lthresh <- 0.6

#Number of PCS components to use
nrPCs <- 9

#Z score threshold for extreme spot cell count
SCCZscoreThresh <- 3

#Spot cell count threshold for HF dataset
HFSCCThresh <- 20

#Replicate count threshold for HF Dataset
HFRepThresh <- 3

# https://meplincs.ohsu.edu/webclient/

if(!Segmentation=="v1"){
  l3$OmeroDetailURL <- paste0('<a href="https://meplincs.ohsu.edu/webclient/img_detail/',l3$ImageID,'/"',' target="_blank">Omero</a>')
  l3$OmeroThumbnailURL <- paste0('<a href="https://meplincs.ohsu.edu/webclient/render_thumbnail/',l3$ImageID,'/"',' target="_blank">Omero</a>')
  l3$OmeroImageURL <- paste0('<a href="https://meplincs.ohsu.edu/webclient/render_image/',l3$ImageID,'/"',' target="_blank">Omero</a>')
}

```

###Spot Cell Count by Pin Across All Wells of Each Plate

```{r,  fig.height=4}
dt <- unique(l3[,.(Barcode,Block,Spot_PA_SpotCellCount,Ligand)])
p <- ggplot(dt, aes(x = factor(Block), y = Spot_PA_SpotCellCount))+
  geom_boxplot(fill="transparent", outlier.colour = NA)+
  facet_wrap(~Barcode)+
  coord_cartesian(ylim=c(0,400))+
  ggtitle(paste("Spot Cell Count Distributions by Pin"))+
  xlab("Print Head Pin")+ylab("Spot Cell Count")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=1, size=rel(.7)), axis.text.y = element_text(angle = 0, vjust = 0.5, hjust=1, size=rel(.7)), plot.title = element_text(size = rel(.7)),legend.text=element_text(size = rel(1)),legend.title=element_text(size = rel(1)))
p <- p + geom_jitter(size=.1, alpha=.2)
p


```



###Spot Cell Count by Pin by Wells of Each Plate

```{r,  fig.height=16}
dt <- unique(l3[,.(Barcode,Well,Block,Spot_PA_SpotCellCount,Ligand)])
p <- ggplot(dt, aes(x = factor(Block), y = Spot_PA_SpotCellCount))+
  geom_boxplot(fill="transparent", outlier.colour = NA)+
  facet_grid(Well~Barcode)+
  coord_cartesian(ylim=c(0,400))+
  ggtitle(paste("Spot Cell Count Distributions by Pin"))+
  xlab("Print Head Pin")+ylab("Spot Cell Count")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=1, size=rel(.7)), axis.text.y = element_text(angle = 0, vjust = 0.5, hjust=1, size=rel(.7)), plot.title = element_text(size = rel(.7)),legend.text=element_text(size = rel(1)),legend.title=element_text(size = rel(1)))
p <- p + geom_jitter(size=.1, alpha=.2)
p


```


###Selecting pins with similar cell counts


```{r,  fig.height=4, fig.width=4}
normSCC <- function(x){
  x/numericMedian(x)
}
dt <- unique(l3[,.(Barcode,Block,Spot_PA_SpotCellCount)])
dt <- dt[, .(PinMedian =numericMedian(Spot_PA_SpotCellCount)), by=c("Barcode","Block")]
dt <- dt[,PinMedianNorm := normSCC(PinMedian),by="Barcode"]
dtc <- dcast(dt, Block~Barcode,value.var = "PinMedianNorm")

p <- ggplot(dtc, aes(x = LI8X00850, y=LI8X00860, label=Block))+
  geom_point()+
  geom_abline(slope=1, intercept = c(-.05,0,.05))+
  geom_vline(xintercept = c(.9,1.16))+
    geom_hline(yintercept = c(.9,1.16))+
 coord_cartesian(xlim=c(.7,1.4),ylim=c(.7,1.4))+
  ggtitle(paste("Normalized Spot Cell Count Medians by Pin"))

ggplotly(p)

setnames(dtc,"Block","Pin")
#unique(dtc[LI8X00850<1.15&LI8X00850>.9&LI8X00860<1.15&LI8X00860>.9,c("Pin")])

```


Using the figure and table above, the primary 12 pins from the 860 printhead layout are `r unlist(unique(dtc[LI8X00850<=1.10&LI8X00850>.9&LI8X00860<=1.10&LI8X00860>.9,c("Pin")]))` and pins `r unlist(unique(dtc[LI8X00850<=1.16&LI8X00850>.9&LI8X00860<1.15&LI8X00860>1.1,c("Pin")]))` should be used as spares for this group.


