
```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8,
                      echo=FALSE, warning=FALSE, message=FALSE)
```


```{r }
#Author: Mark Dane, copyright 2015

source("./MEPLINCSFunctions.R")

```



```{r setup,cache=FALSE}
library("ggplot2")
library("data.table")
library("MEMA")
library("grid")
library("knitr")
library("gplots")
library("RColorBrewer")
library(DT)
library(d3heatmap)
library(plotly)
library(corrplot)
library(Rtsne)

#Setup colors for Barcode and text in all heatmaps
selDark2 <- colorRampPalette(brewer.pal(8,"Dark2"))
plateCol = selDark2(8)
hmcols<-colorRampPalette(c("blue","white","red"))(16)

l3 <- fread(paste0("./",cellLine,"/",ss,"/AnnotatedData/",cellLine, "_",ss,"_",rawDataVersion,"_",analysisVersion,"_Level3.txt"), showProgress = FALSE)
l4 <- fread(paste0("./",cellLine,"/",ss,"/AnnotatedData/",cellLine, "_",ss,"_",rawDataVersion,"_",analysisVersion,"_Level4.txt"), showProgress = FALSE)

barcodes <- sort(unique(l3$Barcode))


#Set a threshold for filtering wells on their QA score
wellQAThresh <- 0.8

#TODO: Read this from Level 3 data
lthresh <- 0.6

#Number of PCS components to use
nrPCs <- 9

#Z score threshold for extreme spot cell count
SCCZscoreThresh <- 3

#Spot cell count threshold for HF dataset
HFSCCThresh <- 20

#Replicate count threshold for HF Dataset
HFRepThresh <- 3

# https://meplincs.ohsu.edu/webclient/

if(!analysisVersion=="v1"){
  l3$OmeroDetailURL <- paste0('<a href="https://meplincs.ohsu.edu/webclient/img_detail/',l3$ImageID,'/"',' target="_blank">Omero</a>')
  l3$OmeroThumbnailURL <- paste0('<a href="https://meplincs.ohsu.edu/webclient/render_thumbnail/',l3$ImageID,'/"',' target="_blank">Omero</a>')
  l3$OmeroImageURL <- paste0('<a href="https://meplincs.ohsu.edu/webclient/render_image/',l3$ImageID,'/"',' target="_blank">Omero</a>')
}

```


```{r Filtering}

#Remove the fiducial and blank data
setkey(l3,ECMp)
l3F <- l3[!grepl("fiducial|Fiducial|blank|PBS",l3$ECMp),]
l3F <- l3F[!grepl("FBS", l3F$Ligand)]

#Remove failed QA wells
l3F <- l3F[!l3F$QA_LowWellQA]
l3F <- l3F[l3F$QAScore>wellQAThresh]
l4F <- createl4(l3F,  seNames=c("DNA2N","SpotCellCount","Edu","MitoTracker","KRT","Lineage","Fibrillarin"))
#Add Robust Z Scores of the normalized Spot Cell Counts #across the entire staining set
l4F <- l4F[,Spot_PA_SpotCellCountLog2RUV3Loess_RobustZ := RZScore(Spot_PA_SpotCellCountLog2RUV3Loess)]

if (grepl("SS2",ss)){
  #Add Robust Z Score of the Edu Signal
  l4F <- l4F[,Nuclei_PA_Gated_EduPositiveProportionRUV3Loess_RobustZ := RZScore(Nuclei_PA_Gated_EduPositiveProportionRUV3Loess)]
}

if (grepl("SS3",ss)){
  #Add Robust Z Scores of the normalized lineage ratios
  l4F <- l4F[, Cytoplasm_PA_Intensity_LineageRatioRUV3Loess_RobustZ:= RZScore(Cytoplasm_PA_Intensity_LineageRatioRUV3Loess)]
  
}

```


```{r SCCHeatmapFull, fig.width=8, fig.height=5}
#Cast to get ligands into columns
df <- dcast(data.frame(l4F[,list(ECMp,Ligand,Spot_PA_SpotCellCountLog2RUV3Loess,Barcode)]),ECMp~Ligand, value.var = "Spot_PA_SpotCellCountLog2RUV3Loess")

rownames(df) <- df$ECMp
df <- df[,!grepl("ECMp",names(df))]

try(d3heatmap(dfZoom(df, .05, .95), colors=hmcols, xaxis_font_size="7pt", yaxis_font_size="6pt"), TRUE)

```

